{
 "title": "Tailscale Metrics",
 "tags": [
  "tailscale",
  "networking"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "path",
    "query": {
     "query": "label_values(tailscaled_inbound_packets_total,path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tailscaled_inbound_bytes_total[5m]))",
     "legendFormat": "Inbound Bytes"
    },
    {
     "expr": "sum(rate(tailscaled_outbound_bytes_total[5m]))",
     "legendFormat": "Outbound Bytes"
    }
   ]
  },
  {
   "title": "Packets by Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tailscaled_inbound_packets_total{path=~\"$path\"}[5m])",
     "legendFormat": "inbound - {{path}}"
    },
    {
     "expr": "rate(tailscaled_outbound_packets_total{path=~\"$path\"}[5m])",
     "legendFormat": "outbound - {{path}}"
    }
   ]
  },
  {
   "title": "Health Warnings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tailscaled_health_messages{type=\"warning\"}"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tailscaled_advertised_routes", "legendFormat": "Advertised Routes" },
    { "expr": "tailscaled_approved_routes", "legendFormat": "Approved Routes" }
   ]
  }
 ]
}