#!/usr/bin/env -S just --justfile

## repo configuration
sub-update:
  cd .. && git submodule update --init --recursive

## nix installation

## nix updates
hostname := `hostname | cut -d "." -f 1`
[linux]
switch target_host=hostname:
  cd nix && sudo nixos-rebuild switch --flake .#{{target_host}}

## copy docker compose yaml to remote host via Ansible
compose HOST *V:
  ansible-playbook ansible/playbook.yaml --limit {{HOST}} --tags compose {{V}}
